version: '3.8'
services:
  zookeeper:    
    image: wurstmeister/zookeeper:latest    
    container_name: zookeeper    
    ports:      
      - "2181:2181"  

  kafka:    
    image: wurstmeister/kafka:latest    
    container_name: kafka    
    ports:
      - "9092:9092"    
    environment:      
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181    
    volumes:      
      - /var/run/docker.sock:/var/run/docker.sock

  mysql:
    container_name: mysql
    image: mysql:latest
    volumes:
      - ./mysql/demo/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - ./mysql/demo/var/lib/mysql:/var/lib/mysql
      - ./mysql/demo/var/log/mysql:/var/log/mysql
    environment:
      - MYSQL_DATABASE=toeicdoit_db
      - MYSQL_ROOT_PASSWORD=sitetoeicdoit
      - MYSQL_ROOT_HOST=%
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3306:3306"
    restart: always
    
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=sitetoeicdoit
      - MONGO_INITDB_DATABASE=toeicdoit_db
    restart: always

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --requirepass sitetoeicdoit
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always

  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: sitetoeicdoit
      POSTGRES_DB: toeicdoit_db
    restart: always