services:
  eureka:
    build:
      context: eureka-service
      dockerfile: Dockerfile
    image: toeicdoit/eureka:latest
    container_name: eureka
    ports:
      - 8761:8761
    networks:
      - toeicdoit-net
    depends_on:
      - config
    hostname: eureka

  gateway:
    build:
      context: gateway-service
      dockerfile: Dockerfile
    image: toeicdoit/gateway:latest
    container_name: gateway
    ports:
      - 8000:8000
    networks:
      - toeicdoit-net
    depends_on:
      - eureka
      - redis
    hostname: gateway

  # user:
  #   build:
  #     context: user-service
  #     dockerfile: Dockerfile
  #   image: toeicdoit/user:latest
  #   container_name: user
  #   ports:
  #   - 8091:8091
  #   networks:
  #     - toeicdoit-net
  #   depends_on:
  #     - eureka
  #     - mysql
  #     - mongodb
  #   hostname: user

  # chat:
  #   build:
  #     context: chat-service
  #     dockerfile: Dockerfile
  #   image: toeicdoit/chat:latest
  #   container_name: chat
  #   ports:
  #   - 8088:8088
  #   networks:
  #     - toeicdoit-net
  #   depends_on:
  #     - eureka
  #     - mongodb
  #     - kafka
  #   hostname: chat

  # toeic:
  #   build:
  #     context: toeic-service
  #     dockerfile: Dockerfile
  #   image: toeicdoit/toeic:latest
  #   container_name: toeic
  #   ports:
  #   - 8089:8089
  #   networks:
  #     - toeicdoit-net
  #   depends_on:
  #     - user
  #   hostname: toeic

  # tx:
  #   build:
  #     context: tx-service
  #     dockerfile: Dockerfile
  #   image: toeicdoit/tx:latest
  #   container_name: tx
  #   ports:
  #   - 8090:8090
  #   networks:
  #     - toeicdoit-net
  #   depends_on:
  #     - user
  #   hostname: tx


networks:
  toeicdoit-net:
    driver: bridge