apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-sa
  namespace: jenkins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: jenkins
  name: jenkins-role
rules:
  - apiGroups: ["extensions", ""]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-rolebinding
  namespace: jenkins
subjects:
  - kind: ServiceAccount
    name: jenkins-sa
roleRef:
  kind: Role
  name: jenkins-role
  apiGroup: rbac.authorization.k8s.io