apiVersion: v1
kind: Service
metadata:
  name: toeicdoit-service
  labels:
    app: toeicdoit-service
spec:
  type: LoadBalancer
  ports:
  - name: gateway
    protocol: TCP 
    port: 80
    targetPort: 80
  - name: eureka
    protocol: TCP 
    port: 8761
    targetPort: 8761
  - name: user
    protocol: TCP 
    port: 8091
    targetPort: 8091
  - name: chat
    protocol: TCP 
    port: 8088
    targetPort: 8088
  - name: toeic
    protocol: TCP 
    port: 8089
    targetPort: 8089
  - name: tx
    protocol: TCP 
    port: 8090
    targetPort: 8090
  selector:
    app: toeicdoit
    