# show tables;
insert into user_model (id, email, password, name, registration) values (1, 'admin@test.com', '1234', '관리자', 'LOCAL');
insert into calendar_model (user_id, is_all_day) values (1, true);
insert into role_model (role, user_id) values (1, 1);

# insert into user_model (email, password, profile, name, phone, toeic_level, registration, created_at, updated_at) values ('eyele1@t.co', '$2a$04$GRrg/R0OhJ6FKm.klN0vDulLU59qZ5Dp6otnjrpqMFfA13qOQ2s1.', 'http://dummyimage.com/139x100.png/dddddd/000000', 'Elinore Yele', '3211114310', 2, 'LOCAL', now(), now());
# insert into user_model (email, password, profile, name, phone, toeic_level, registration, created_at, updated_at) values ('alamminam2@army.mil', '$2a$04$9aCleBL.T9C3sNzkBWZMq.1JI1fdK2czsPVcDPIMdUnSWfPIXjYlW', 'http://dummyimage.com/193x100.png/ff4444/ffffff', 'Alasteir Lamminam', '2226191359', 3, 'LOCAL', now(), now());
# insert into user_model (email, password, profile, name, phone, toeic_level, registration, created_at, updated_at) values ('bbaigrie3@opera.com', '$2a$04$4hBdKSZ2nJfyb9.EEs6L4OkPKlHrI3xjUSG7BurrF8Y0w226x.tRm', 'http://dummyimage.com/195x100.png/5fa2dd/ffffff', 'Bink Baigrie', '8801555178', 4, 'LOCAL', now(), now());
# insert into user_model (email, password, profile, name, phone, toeic_level, registration, created_at, updated_at) values ('flikely4@xinhuanet.com', '$2a$04$WduU5aA8EoB/HiDr6LtOkuH2iia1mWqi27KDVuEhJlpqHpIBnAh5y', 'http://dummyimage.com/202x100.png/ff4444/ffffff', 'Fabe Likely', '1871819574', 5, 'LOCAL', now(), now());
# insert into user_model (email, password, profile, name, phone, toeic_level, registration, created_at, updated_at) values ('tzealey5@xrea.com', '$2a$04$ZyESXReScHSl7D1PvfnQDunmDGSZhz2kWShg7Mj.toBHCk4ipRX.2', 'http://dummyimage.com/235x100.png/5fa2dd/ffffff', 'Tailor Zealey', '3665566580', 6, 'GOOGLE', now(), now());
# insert into user_model (email, password, profile, name, phone, toeic_level, registration, created_at, updated_at) values ('ccutill6@tinypic.com', '$2a$04$oqT7U7knHwURib95oGx/3uXguhDaaeTzN35vS873aXUw64UUIR5ai', 'http://dummyimage.com/147x100.png/5fa2dd/ffffff', 'Caesar Cutill', '4578758122', 7, 'GOOGLE', now(), now());
# insert into user_model (email, password, profile, name, phone, toeic_level, registration, created_at, updated_at) values ('knoor7@samsung.com', '$2a$04$XY/ZmzAfa1xR.Nz6fG/vE.B6eWDhznyi5osCYJiFeQ/XTaFFIKB.q', 'http://dummyimage.com/234x100.png/5fa2dd/ffffff', 'Kienan Noor', '9781845771', 8, 'GOOGLE', now(), now());
# insert into user_model (email, password, profile, name, phone, toeic_level, registration, created_at, updated_at) values ('dkhotler8@cafepress.com', '$2a$04$IryFLei7uE8BtU58Ny9t6eSSeBQC2GeTCCQkRZ5NHt6c9h1QebDmq', 'http://dummyimage.com/148x100.png/ff4444/ffffff', 'Dorelle Khotler', '2401346418', 9, 'GOOGLE', now(), now());
# insert into user_model (email, password, profile, name, phone, toeic_level, registration, created_at, updated_at) values ('rbanstead9@abc.net.au', '$2a$04$x7eWO0rozwyCFo3TUBkEr.Dj.3okhMToGWUMuyW4W6tx7QDZdwwOu', 'http://dummyimage.com/209x100.png/dddddd/000000', 'Roy Banstead', '9579000273', 10, 'GOOGLE', now(), now());
#
# insert into board_model (title, content, type, user_Id, created_at, updated_at) values ('Ford', 'Mungos mungo', '문의', 1, now(), now());
# insert into board_model (title, content, type, user_Id, created_at, updated_at) values ('Chrysler', 'Pteronura brasiliensis', '문의', 2, now(), now());
# insert into board_model (title, content, type, user_Id, created_at, updated_at) values ('Lexus', 'Bucephala clangula', '문의', 3, now(), now());
# insert into board_model (title, content, type, user_Id, created_at, updated_at) values ('Porsche', 'Damaliscus lunatus', '공지', 4, now(), now());
# insert into board_model (title, content, type, user_Id, created_at, updated_at) values ('Cadillac', 'Macropus robustus', '공지', 5, now(), now());
# insert into board_model (title, content, type, user_Id, created_at, updated_at) values ('GMC', 'Carduelis pinus', '공지', 6, now(), now());
# insert into board_model (title, content, type, user_Id, created_at, updated_at) values ('Nissan', 'Tiliqua scincoides', '자유', 7, now(), now());
# insert into board_model (title, content, type, user_Id, created_at, updated_at) values ('Bentley', 'Castor fiber', '자유', 8, now(), now());
# insert into board_model (title, content, type, user_Id, created_at, updated_at) values ('Ford', 'Bugeranus caruncalatus', '자유', 9, now(), now());
# insert into board_model (title, content, type, user_Id, created_at, updated_at) values ('Pontiac', 'Salvadora hexalepis', '자유', 10, now(), now());
# insert into board_model (title, content, type, user_Id, created_at, updated_at) values ('Pontiac', 'Salvadora hexalepis', '자유', 10, now(), now());
# insert into board_model (title, content, type, user_Id, created_at, updated_at) values ('Pontiac', 'Salvadora hexalepis', '자유', 10, now(), now());
#
# insert into role_model (role, user_id) values (0, 1);
# insert into role_model (role, user_id) values (1, 2);
# insert into role_model (role, user_id) values (0, 3);
# insert into role_model (role, user_id) values (0, 4);
# insert into role_model (role, user_id) values (1, 5);
# insert into role_model (role, user_id) values (1, 6);
# insert into role_model (role, user_id) values (0, 7);
# insert into role_model (role, user_id) values (1, 8);
# insert into role_model (role, user_id) values (1, 9);
# insert into role_model (role, user_id) values (0, 10);
# insert into role_model (role, user_id) values (1, 10);
# insert into role_model (role, user_id) values (0, 10);
#
# insert into calendar_model (user_id, title, is_all_day, start_time, end_time, created_at, updated_at) values (1, 'BCF', 0, now(), now(), now(), now());
# insert into calendar_model (user_id, title, is_all_day, start_time, end_time, created_at, updated_at) values (2, 'EPU', 1, now(), now(), now(), now());
# insert into calendar_model (user_id, title, is_all_day, start_time, end_time, created_at, updated_at) values (3, 'LHC', 1, now(), now(), now(), now());
# insert into calendar_model (user_id, title, is_all_day, start_time, end_time, created_at, updated_at) values (4, 'CNL', 0, now(), now(), now(), now());
# insert into calendar_model (user_id, title, is_all_day, start_time, end_time, created_at, updated_at) values (5, 'TJQ', 1, now(), now(), now(), now());
# insert into calendar_model (user_id, title, is_all_day, start_time, end_time, created_at, updated_at) values (6, 'YXL', 0, now(), now(), now(), now());
# insert into calendar_model (user_id, title, is_all_day, start_time, end_time, created_at, updated_at) values (7, 'COE', 1, now(), now(), now(), now());
# insert into calendar_model (user_id, title, is_all_day, start_time, end_time, created_at, updated_at) values (8, 'AJA', 0, now(), now(), now(), now());
# insert into calendar_model (user_id, title, is_all_day, start_time, end_time, created_at, updated_at) values (9, 'LVA', 1, now(), now(), now(), now());
# insert into calendar_model (user_id, title, is_all_day, start_time, end_time, created_at, updated_at) values (10, 'MBE', 0, now(), now(), now(), now());