# eureka:
#     client:
#         registerWithEureka: false
#         fetchRegistry: false
#         serviceUrl:
#             defaultZone: http://localhost:8761/eureka/

server:
    port: 8761
spring:
    application:
        name: eureka-service
    profiles:
        active: local
    config:
        import: optional:configserver:http://localhost:8888